//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicerieMvcEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int ID { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> Qte { get; set; }
        public Nullable<int> IDFournisseur { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
